preserve_hierarchy: 1
files:
  - source: /src/PikseraPackages/Translation/resources/lang/en_US.json
    translation: /src/PikseraPackages/Translation/resources/lang/%locale_with_underscore%.%file_extension%
    first_line_contains_header:
    scheme: 'source_phrase,translation'
